apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l89rcmkpw-go 
  janus-idp.io/tekton: l89rcmkpw-go
  backstage.io/kubernetes-id: l89rcmkpw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l89rcmkpw-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  